sudo: required

addons: 
  chrome: stable

language: node_js

node_js:
  - "12.2.0"

  script: echo "Running tests against $(node -v) ..."

branches: 
 - only:
    - master

before_install: echo "Before Dependancy Install By Suraj..."

before_script: 
    - npm install -g @angular/cli
    - npm install -g firebase-tools 

script: 
  - npm install
  - ng build --prod
cache: 
  - npm

after_success: 
  - deploy:  
      - firebase deploy --token $FIREBASE_TOKEN

after_success:
  script: 
  - ng build --prod --base-href https://iamsurajdc.github.io/Grocery-Application/ 
  deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master